<?php
    /**
     * @var GaussDev\CategoryWidget\Widget\Category $block
     * @var \Magento\Catalog\Model\Product $_item
     */

        $type = 'widget-product-grid';
        $slider_id = "gauss_category_slider";
        $image = 'new_products_content_widget_grid';
?>

<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <div class="category_slider_widget">
        <?php if($block->getTitle()): ?>
            <div class="block-title">
                <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $block->getTitle(); ?></strong>
            </div>
        <?php endif; ?>
         <div class="block-content">
             <div id="<?php echo $slider_id ?>" class="product-items widget-product-grid owl-carousel">
            <?php foreach ($block->getProductCollection() as $_item): ?>
                <div class="product_info">
                    <a href="<?php echo $block->getProducturl($_item) ?>" class="product_item_photo">
                        <?php echo $block->getImage($_item, $image)->toHtml() ?>
                    </a>
                </div>
                 <div class="product-item-details">
                     <strong class="product-item-name">
                         <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                            href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                            class="product-item-link">
                             <?php echo $block->escapeHtml($_item->getName()) ?>
                         </a>
                     </strong>
<!--                     --><?php //echo $block->getProductPriceHtml($_item, $type); ?>
                 </div>
                 <?php if($block->getCart()): ?>
                    <div class="actions-primary">
                        <?php if ($_item->isSaleable()): ?>
                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                <button class="action tocart primary"
                                        data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                </button>
                            <?php else: ?>
                                <?php
                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                ?>
                                <button class="action tocart primary"
                                        data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                </button>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if ($_item->getIsSalable()): ?>
                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                            <?php else: ?>
                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                 <?php endif; ?>
            <?php endforeach; ?>
             </div>
         </div>
    </div>

    <script>
        require([
            'jquery',
            'owlcarousel'
        ], function ($) {
            $(function () {
                $("<?php echo $slider_id ?>").owlCarousel({
                    loop: <?php echo $block->getLoop() ?>,
                    nav: <?php echo $block->getNav() ?>,
                    dots: <?php echo $block->getDots() ?>,
                    items: <?php echo $block->getItemsPerSlide() ?>
                });
            });
        });
    </script>
<?php endif; ?>